export const products = [
  
  {
      id: 1,
      name: "Souls",
      price: 349.99,
      color: "Negro",
      images: [
        "/images/Souls_Trasera.png",
        "/images/Souls_Frontal.png",
        "/images/Render_Souls.png",
      ],
      stockBySize: {
       S: 0,
      M: 0,
      L: 0,
      XL: 0,
      },
      sizes: ["S", "M", "L", "XL"],
      colors: ["Black", "White"],
    },
    {
        id: 2,
        name: "Nine",
        price: 349.99,
        color: "Negro",
        images: [
          "/images/Nine_Trasero.png",
          "/images/Nine_Frontal.png",
          "/images/Render_Nine.png",
        ],
        stockBySize: {
          S: 0,
      M: 0,
      L: 0,
      XL: 0,
        },
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "White"],
      },
  {
    id: 3,
    name: "L art Est Tout",
    price: 499.99,
    color: "Flores",
    images: [
      "/images/Flores_Trasera.png",
      "/images/Flores_Frontal.png",
      "/images/Render_Flores.png"
    ],
    stockBySize: {
     S: 0,
      M: 0,
      L: 0,
      XL: 0,
    },
    sizes: ["S", "M", "L", "XL"],
    colors: ["Red", "Blue"],
    desc:"",
  },
    {
      id: 4,
      name: "Make Money",
      price: 299.99,
      color: "Blanco y Rojo",
      images: [
        "/images/Make_Money_White_Rojo_Trasera.png",
        "/images/Make_Money_Blanco_Rojo_Frontal.png",
        "/images/Render_Blanco_Rojo.png"
      ],
      stockBySize: {
        S: 0,
      M: 0,
      L: 0,
      XL: 0,
      },
      sizes: ["S", "M", "L", "XL"],
      colors: ["Red", "Blue"],
      desc:"",
    },
    {
      id: 5,
      name: "Make Money",
      price: 299.99,
      color: "Gris y Rojo",
      images: [
        "/images/Make_Money_Gris_Rojo_Trasera.png",
        "/images/Make_Money_Gris_Rojo_Frontal.png",
        "/images/Render_Gris_Rojo.png"
      ],
      stockBySize: {
        S: 0,
      M: 0,
      L: 0,
      XL: 0,
      },
      sizes: ["S", "M", "L", "XL"],
      colors: ["Red", "Blue"],
      desc:"",
    },
    {
      id: 6,
      name: "Make Money",
      price: 299.99,
      color: "Gris y Rosa",
      images: [
        "/images/Make_Money_Gris_Rosa_Trasera.png",
        "/images/Make_Money_Gris_Rosa_Frontal.png",
        "/images/Render_Gris_Rosa.png"
      ],
      stockBySize: {
        S: 0,
      M: 0,
      L: 0,
      XL: 0,
      },
      sizes: ["S", "M", "L", "XL"],
      colors: ["Red", "Blue"],
      desc:"",
    },
    {
      id: 8,
      name: "Make Money",
      price: 299.99,
      color: "Negro y Rojo",
      images: [
        "/images/Make_Money_Negra_Rojo_Trasera.png",
        "/images/Make_Money_Negra_Rojo_Frontal.png",
      ],
      stockBySize: {
        S: 0,
      M: 0,
      L: 0,
      XL: 0,
      },
      sizes: ["S", "M", "L", "XL"],
      colors: ["Red", "Blue"],
      desc:"",
    },
    {
      id: 9,
      name: "Make Money",
      price: 299.99,
      color: "Negro y Gris",
      images: [
        "/images/Make_Money_Negro_Gris_Trasera.png",
        "/images/Make_Money_Negro_Gris_Frontal.png",
        "/images/Render_Negro_Gris.png",
      ],
      stockBySize: {
        S: 0,
      M: 0,
      L: 0,
      XL: 0,
      },
      sizes: ["S", "M", "L", "XL"],
      colors: ["Red", "Blue"],
      desc:"",
    },
    {
      id: 10,
      name: "Make Money",
      price: 299.99,
      color: "Negro y Rosa",
      images: [
        "/images/Make_Money_Negro_Rosa_Trasera.png",
        "/images/Make_Money_Negro_Rosa_Frontal.png",
        "/images/Render_Negro_Rosa.png",
      ],
      stockBySize: {
       S: 0,
      M: 0,
      L: 0,
      XL: 0,
      },
      sizes: ["S", "M", "L", "XL"],
      colors: ["Red", "Blue"],
      desc:"",
    },
    {
      id: 11,
      name: "Luck to You",
      price: 299.99,
      color: "Blanco y Negro",
      images: [
        "/images/Angel _Blanco_Negro_Trasera.png",
        "/images/Angel _Blanco_Negro_Frontal.png",
        "/images/Render_Angel_Blanco.png",
      ],
      stockBySize: {
       S: 0,
      M: 0,
      L: 0,
      XL: 0,
      },
      sizes: ["S", "M", "L", "XL"],
      colors: ["Red", "Blue"],
      desc:"",
    },
    {
      id: 12,
      name: "Luck to You",
      price: 299.99,
      color: "Gris y Negro",
      images: [
        "/images/Angel _Gris_Negro_Trasera.png",
        "/images/Angel _Gris_Negro_Frontal.png",
        "/images/Render_Angel_gris.png",
      ],
      stockBySize: {
        S: 0,
        M: 0,
        L: 0,
        XL: 0,
      },
      sizes: ["S", "M", "L", "XL"],
      colors: ["Red", "Blue"],
      desc:"",
    },
    {
      id: 13,
      name: "Luck to You",
      price: 299.99,
      color: "Negro y Gris",
      images: [
        "/images/Angel _Negro_Gris_Trasera.png",
        "/images/Angel _Negro_Gris_Frontal.png",
        "/images/Render_Angel_Negro.png",
      ],
      stockBySize: {
       S: 0,
      M: 0,
      L: 0,
      XL: 0,
      },
      sizes: ["S", "M", "L", "XL"],
      colors: ["Red", "Blue"],
      desc:"",
    },
    {
      id: 14,
      name: "Santal",
      price: 299.99,
      color: "Negro",
      images: [
        "/images/Santal_Negro_Trasera.png",
        "/images/Santal_Negro_Frontal.png",
        "/images/Modelo_santal_Negro1.jpg",
        "/images/Modelo_santal_Negro2.jpg",
      ],
      stockBySize: {
        S: 0,
        M: 0,
        L: 0,
        XL: 0,
      },
      sizes: ["S", "M", "L", "XL"],
      colors: ["Red", "Blue"],
      desc:"",
    },
    {
      id: 15,
      name: "Santal",
      price: 299.99,
      color: "Beige",
      images: [
        "/images/Santal_Beige_Trasera.png",
        "/images/Santal_Beige_Frontal.png",
        "/images/Render_Santal_Beige.png",
      ],
      stockBySize: {
        S: 0,
      M: 0,
      L: 0,
      XL: 0,
      },
      sizes: ["S", "M", "L", "XL"],
      colors: ["Red", "Blue"],
      desc:"",
    },
    {
      id: 16,
      name: "Santal",
      price: 299.99,
      color: "Blanco",
      images: [
        "/images/Santal_Blanco_Trasera.png",
        "/images/Santal_Blanco_Frontal.png",
        "/images/Render_Santal_Blanco.png",
      ],
      stockBySize: {
       S: 0,
      M: 0,
      L: 0,
      XL: 0,
      },
      sizes: ["S", "M", "L", "XL"],
      colors: ["Red", "Blue"],
      desc:"",
    },

  ]

export const newDrops = [
  // {
  //   id: 17,
  //   name: "Souls",
  //   price: 349.99,
  //   images: [
  //     "/images/newdrop2.jpeg",
  //     "/images/souls.png"
  //   ] ,
  //   stockBySize: {
  //     S: 0,
  //     M: 10,
  //     L: 5,
  //     XL: 0,
  //   },
  //   sizes: ["S", "M", "L", "XL"],
  //   colors: ["Black"],
  //   desc:"",
  // },
 
  {
    id: 2,
    name: "Nine",
    price: 349.99,
    images: [
      "/images/Nine_Trasero.png",
      "/images/Nine_Frontal.png",
      "/images/Render_Nine.png",
    ],
    stockBySize: {
      S: 0,
      M: 0,
      L: 0,
      XL: 0,
    },
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White"],
  },
  {
    id: 18,
    name: "Souls",
    price: 349.99,
    images: [
      "/images/souls.png",
    ],
    stockBySize: {
     S: 0,
      M: 0,
      L: 0,
      XL: 0,
    },
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White"],
    desc:"",
  },
  // {
  //   id: 19,
  //   name: "Souls",
  //   price: 349.99,
  //   images: [
  //     "/images/newdrop3.jpeg",
  //     "/images/souls.png"
  //   ],
  //   stockBySize: {
  //     S: 0,
  //     M: 0,
  //     L: 5,
  //     XL: 0,
  //   },
  //   sizes: ["S", "M", "L", "XL"],
  //   colors: ["Red", "Blue"],
  //   desc:"",
  // },
];
